CREATE DATABASE BeatSync;

USE BeatSync;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(35) NOT NULL,
    email VARCHAR(35) NOT NULL,
    dataNasc DATE,
    gender VARCHAR(35) NOT NULL,
    senha VARCHAR(20) NOT NULL
);

CREATE TABLE music (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    artista VARCHAR(200) NOT NULL,
    genderM VARCHAR(200) NOT NULL,
    album VARCHAR(200) NOT NULL
);